name: Documentation
on:
  push:
    branches:
      - 'master'
    paths:
      - '**.properties'
      - '**/CreateUITable.java'

jobs:
  gradle:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        if: runner.os == 'macOS'
        with:
          xcode-version: '12.1'
      - name: Build documentation
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :darklaf-core:makeDocumentation -PskipAutostyle -x test
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Upload documentation
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-documentation
          path: build/documentation
